opts.VariableNames = ["Date" , ...
"Time" , ...
"T_Oven-01" , ...
"T_Oven-02" , ...
"T_A-01" , ...
"T_A-02" , ...
"T_A-03" , ...
"T_A-04" , ...
"T_A-05" , ...
"T_A-06" , ...
"T_C-01" , ...
"T_C-02" , ...
"T_C-03" , ...
"T_C-04" , ...
"T_C-05" , ...
"T_C-06" , ...
"T_A_In" , ...
"T_A_Out" , ...
"T_C_In" , ...
"T_C_Out" , ...
"T Humidifier" , ...
"Vol H2O (actual)", ...
"p Hum (actual)" , ...
"i_target" , ...
"i_act" , ...
"i_act2" , ...
"A" , ...
"V_act" , ...
"N2_tar" , ...
"N2_act" , ...
"H2_tar" , ...
"H2_act" , ...
"CO_tar" , ...
"CO_act" , ...
"CO2_tar" , ...
"CO2_act" , ...
"CH4_tar" , ...
"CH4_act" , ...
"RG_tar" , ...
"RG_act" , ...
"QQ-1" , ...
"QQ-2" , ...
"Air_tar" , ...
"Air_act" , ...
"O2_tar" , ...
"O2_act" , ...
"N2_Air_tar", ...
"N2_Air_act" , ...
"QQ-3" , ...
"v_H2_act" , ...
"v_CO_act" , ...
"v_CO2_act" , ...
"v_CH4_act" , ...
"v_O2_act" , ...
"QQ-4" , ...
"p_atm" , ...
"v_O2_cath" , ...
"stat-GAS-SUPPLY" , ...
"stat-SOFC-OVEN" , ...
"ALARM-fuelflow" , ...
"ALARM-pmax" , ...
"ALARM-dtover1" , ...
"ALARM-dtover1" , ...
"ALARM-load" , ...
"ALARM-modbus" , ...
"QQ-5" , ...
"QQ-6" ];